import { getGroqCompletion } from "./groq";

interface GeneratedThemeTokens {
  name: string;
  slug: string;
  colors: {
    bgPrimary: string;
    bgSecondary: string;
    bgTertiary: string;
    textPrimary: string;
    textSecondary: string;
    accent: string;
    accentSoft: string;
    glassBg: string;
    glassBorder: string;
    ambientA: string;
    ambientB: string;
  };
  mood: string;
}

export async function generateTheme(prompt: string) {
  const systemPrompt = `You are an expert CSS theme generator.
The user will ask for a theme (e.g. "tema gunung berapi" or "volcano theme").
Generate a color palette for a UI theme based on their request.
You MUST ONLY return a valid JSON object matching this schema:
{
  "name": "theme name",
  "slug": "theme-slug",
  "colors": {
    "bgPrimary": "hex",
    "bgSecondary": "hex",
    "bgTertiary": "hex",
    "textPrimary": "hex",
    "textSecondary": "hex",
    "accent": "hex",
    "accentSoft": "hex",
    "glassBg": "rgba string",
    "glassBorder": "rgba string",
    "ambientA": "hex",
    "ambientB": "hex"
  },
  "mood": "short mood description"
}

Do not include any text, markdown formatting, or comments outside the JSON object.`;

  const text = await getGroqCompletion({
    model: "llama-3.3-70b-versatile",
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: prompt }
    ],
    temperature: 0.7,
    max_tokens: 1024,
  });

  const cleaned = text.replace(/^```json\s*/i, "").replace(/\s*```$/i, "").trim();
  const tokens = JSON.parse(cleaned) as GeneratedThemeTokens;

  // Basic validation
  if (!tokens.name || !tokens.colors || !tokens.colors.bgPrimary) {
    throw new Error("Invalid generated theme format");
  }

  const css = `
/* Generated by Serenova — session only */
body {
  background: ${tokens.colors.bgPrimary} !important;
  color: ${tokens.colors.textPrimary} !important;
}
.dark body {
  background: ${tokens.colors.bgPrimary} !important;
  color: ${tokens.colors.textPrimary} !important;
}
.bg-ambient {
  background: radial-gradient(circle at top left, ${tokens.colors.ambientA} 0%, transparent 60%),
              radial-gradient(circle at bottom right, ${tokens.colors.ambientB} 0%, transparent 60%) !important;
}
.dark .bg-ambient {
  background: radial-gradient(circle at top left, ${tokens.colors.ambientA} 0%, transparent 60%),
              radial-gradient(circle at bottom right, ${tokens.colors.ambientB} 0%, transparent 60%) !important;
}
.glass {
  background: ${tokens.colors.glassBg} !important;
  border-color: ${tokens.colors.glassBorder} !important;
}
.dark .glass {
  background: ${tokens.colors.glassBg} !important;
  border-color: ${tokens.colors.glassBorder} !important;
}
`.trim();

  return { tokens, css };
}
